import { Professional } from '../types/professional.types';

export const professionalsData: Professional[] = [
  {
    id: '1',
    // image:"",
    name: 'Olivia Carter',
    rating: 4.9,
    reviews: 132,
    services: 12,
    lowestRate: 45,
  },
  {
    id: '2',
    // image:"",
    name: 'Marcus Allen',
    rating: 4.7,
    reviews: 98,
    services: 8,
    lowestRate: 40,
  },
  {
    id: '3',
    // image:"",
    name: 'Sofia Ramirez',
    rating: 5.0,
    reviews: 210,
    services: 15,
    lowestRate: 55,
  },
  {
    id: '4',
    // image:"",
    name: 'Liam Johnson',
    rating: 4.8,
    reviews: 164,
    services: 10,
    lowestRate: 50,
  },
  {
    id: '5',
    // image:"",
    name: 'Grace Nguyen',
    rating: 4.6,
    reviews: 74,
    services: 6,
    lowestRate: 35,
  },
  {
    id: '6',
    // image:"",
    name: 'Jaden Smith',
    rating: 4.9,
    reviews: 143,
    services: 11,
    lowestRate: 48,
  },
  {
    id: '7',
    // image:"",
    name: 'Amara Okafor',
    rating: 5.0,
    reviews: 196,
    services: 13,
    lowestRate: 60,
  },
  {
    id: '8',
    // image:"",
    name: 'Noah Thompson',
    rating: 4.7,
    reviews: 89,
    services: 7,
    lowestRate: 42,
  },
  {
    id: '9',
    // image:"",
    name: 'Zara Patel',
    rating: 4.8,
    reviews: 120,
    services: 9,
    lowestRate: 47,
  },
];
