import type { Metadata } from 'next';
import './globals.css';
import Header from '@/core/components/Header';
import { Urbanist } from 'next/font/google';

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} font-urbanist antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

function Footer() {
  return (
    <footer className="bg-gray-100 text-center p-4 text-sm text-gray-600">© {new Date().getFullYear()} Tahdaa. All rights reserved.</footer>
  );
}
