import type { Metadata } from 'next';
import './globals.css';
import Header from '@/core/components/Header';
import { Urbanist } from 'next/font/google';
import MuiClientWrapper from './MuiClientWrapper';
import Footer from '@/core/components/Footer';

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} font-urbanist antialiased`}>
        <MuiClientWrapper>
          <Header />
          {children}
          <Footer />
        </MuiClientWrapper>
      </body>
    </html>
  );
}
